### ISSUE TITLE
Addresses are listed in reverse order of frequency

### ISSUE THREAD

**Issue by curiousleo** [aperezdc/notmuch-addrlookup-c#5]
Hi, when I call `notmuch-addrlookup` from Emacs or the command line, it outputs email addresses matching my query in reverse order of frequency. [This patch](https://github.com/aperezdc/notmuch-addrlookup-c/pull/4) fixes the issue for me. Somehow I can't believe that no-one noticed this before, so if this is just affecting me, can you help me figure out what's going on?

**Comment by aperezdc** [comment]
Merged the patch from the associated pull request in `master`. Thanks for the contribution!

**Comment by curiousleo** [comment]
My pleasure :) Thanks for accepting the pull request so quickly!
