### ISSUE TITLE
no angle brackets when inserted

### ISSUE THREAD

**Issue by fommil** [aperezdc/notmuch-addrlookup-c#8]
Thank you for this little app! I'm investigating paying somebody to have it packaged and added to debian  so that everybody can benefit.

I'm using notmuch binary as distributed in debian, and emacs-notmuch / notmuch-address from MELPA (i.e. latest release). But when I tab complete with this plugin the angle brackets are missing from the email address. When I was using goobook, it was working fine so I know it should work.

My full config is available here https://github.com/fommil/dotfiles/blob/master/.emacs.d/init.el#L299

**Comment by bjonnh** [comment]
Same issue here.

**Comment by aperezdc** [comment]
Confirmed, I will have a fix pushed in a few moments.

**Comment by aperezdc** [comment]
Also, tagged version `v5`  containing the fix. I hope this solves your issue. It seems to be working fine for me here. Please re-open the issue if needed :+1:

**Comment by fommil** [comment]
thanks! BTW, I'm paying somebody to package up a bunch of small FOSS projects that I use (like this) for release into Debian unstable... so keep an eye out for them maybe getting in contact :smile:

**Comment by aperezdc** [comment]
@fommil: Neat, please open issues if there are any changes needed to help with packaging. I'll try my best to make the life of packagers a little bit easier ;-)
